from sqlalchemy import select

from app.core.database import SessionLocal
from app.db.init_db import create_mysql_schema
from app.models import DeliveryHub, Product, ProductHubStock
from app.services.products import unique_slug


PRODUCTS = [
    {
        "sku": "ELEC-SAM-GAL-M14",
        "name": "Samsung Galaxy M14 5G 128GB",
        "brand": "Samsung",
        "category": "Electronics",
        "subcategory": "Mobiles",
        "color": "Icy Silver",
        "price": 12499,
        "mrp": 16999,
        "discount_percent": 26,
        "rating": 4.4,
        "inventory": 42,
        "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
        "description": "A reliable 5G smartphone with a large display, long battery life, and smooth everyday performance.",
    },
    {
        "sku": "ELEC-ONE-NORD-BUDS",
        "name": "OnePlus Nord Buds 3 Pro",
        "brand": "OnePlus",
        "category": "Electronics",
        "subcategory": "Audio",
        "color": "Midnight Black",
        "price": 3299,
        "mrp": 4999,
        "discount_percent": 34,
        "rating": 4.3,
        "inventory": 65,
        "image_url": "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80",
        "description": "Wireless earbuds with noise reduction, deep bass, quick charging, and comfortable all-day fit.",
    },
    {
        "sku": "ELEC-BOAT-STORM-CALL",
        "name": "boAt Storm Call Smartwatch",
        "brand": "boAt",
        "category": "Electronics",
        "subcategory": "Wearables",
        "color": "Active Black",
        "price": 1799,
        "mrp": 5990,
        "discount_percent": 70,
        "rating": 4.1,
        "inventory": 88,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
        "description": "A daily fitness smartwatch with calling support, health tracking, and multiple sports modes.",
    },
    {
        "sku": "ELEC-SONY-WH520",
        "name": "Sony WH-CH520 Wireless Headphones",
        "brand": "Sony",
        "category": "Electronics",
        "subcategory": "Audio",
        "color": "Blue",
        "price": 4490,
        "mrp": 5990,
        "discount_percent": 25,
        "rating": 4.5,
        "inventory": 36,
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
        "description": "Lightweight wireless headphones with clear sound, long battery backup, and quick pairing.",
    },
    {
        "sku": "ELEC-MI-POWER-20K",
        "name": "Mi 20000mAh Fast Power Bank",
        "brand": "Mi",
        "category": "Electronics",
        "subcategory": "Accessories",
        "color": "Black",
        "price": 1899,
        "mrp": 2499,
        "discount_percent": 24,
        "rating": 4.2,
        "inventory": 74,
        "image_url": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=80",
        "description": "High-capacity power bank with dual output, fast charging support, and compact travel design.",
    },
    {
        "sku": "LAP-HP-PAV-15-R5",
        "name": "HP Pavilion 15 Ryzen 5 Laptop",
        "brand": "HP",
        "category": "Laptop",
        "subcategory": "Everyday Laptop",
        "color": "Natural Silver",
        "size": "15.6 inch",
        "price": 55990,
        "mrp": 69990,
        "discount_percent": 20,
        "rating": 4.4,
        "inventory": 18,
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
        "description": "A sleek 15.6 inch laptop for productivity, streaming, browsing, and everyday multitasking.",
    },
    {
        "sku": "LAP-LEN-IDEA-SLIM3",
        "name": "Lenovo IdeaPad Slim 3 Intel i5",
        "brand": "Lenovo",
        "category": "Laptop",
        "subcategory": "Student Laptop",
        "color": "Arctic Grey",
        "size": "15.6 inch",
        "price": 47990,
        "mrp": 62990,
        "discount_percent": 24,
        "rating": 4.3,
        "inventory": 22,
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
        "description": "Thin and dependable student laptop with fast storage, crisp display, and comfortable keyboard.",
    },
    {
        "sku": "LAP-ASUS-VIVO-14",
        "name": "ASUS VivoBook 14 OLED",
        "brand": "ASUS",
        "category": "Laptop",
        "subcategory": "OLED Laptop",
        "color": "Quiet Blue",
        "size": "14 inch",
        "price": 62990,
        "mrp": 79990,
        "discount_percent": 21,
        "rating": 4.6,
        "inventory": 14,
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=900&q=80",
        "description": "Compact OLED laptop with vibrant visuals, strong performance, and premium portable styling.",
    },
    {
        "sku": "LAP-DELL-INSP-3530",
        "name": "Dell Inspiron 3530 Core i3",
        "brand": "Dell",
        "category": "Laptop",
        "subcategory": "Office Laptop",
        "color": "Carbon Black",
        "size": "15.6 inch",
        "price": 37990,
        "mrp": 48990,
        "discount_percent": 22,
        "rating": 4.1,
        "inventory": 20,
        "image_url": "https://images.unsplash.com/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=900&q=80",
        "description": "Practical office laptop with reliable performance, full-size display, and essential connectivity.",
    },
    {
        "sku": "GROC-AASHIRVAAD-ATTA-5KG",
        "name": "Aashirvaad Select Sharbati Atta 5 kg",
        "brand": "Aashirvaad",
        "category": "Grocery",
        "subcategory": "Staples",
        "size": "5 kg",
        "price": 289,
        "mrp": 340,
        "discount_percent": 15,
        "rating": 4.5,
        "inventory": 120,
        "image_url": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&q=80",
        "description": "Premium whole wheat atta for soft rotis and daily family meals.",
    },
    {
        "sku": "GROC-DAAWAT-BASMATI-5KG",
        "name": "Daawat Rozana Super Basmati Rice 5 kg",
        "brand": "Daawat",
        "category": "Grocery",
        "subcategory": "Rice",
        "size": "5 kg",
        "price": 499,
        "mrp": 620,
        "discount_percent": 20,
        "rating": 4.4,
        "inventory": 96,
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80",
        "description": "Long-grain basmati rice suitable for biryani, pulao, and everyday meals.",
    },
    {
        "sku": "GROC-FORTUNE-OIL-1L",
        "name": "Fortune Sunlite Refined Oil 1 L",
        "brand": "Fortune",
        "category": "Grocery",
        "subcategory": "Cooking Oil",
        "size": "1 L",
        "price": 139,
        "mrp": 175,
        "discount_percent": 21,
        "rating": 4.2,
        "inventory": 150,
        "image_url": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80",
        "description": "Light refined sunflower oil for daily cooking, frying, and sauteing.",
    },
    {
        "sku": "GROC-AMUL-BUTTER-500G",
        "name": "Amul Pasteurised Butter 500 g",
        "brand": "Amul",
        "category": "Grocery",
        "subcategory": "Dairy",
        "size": "500 g",
        "price": 285,
        "mrp": 300,
        "discount_percent": 5,
        "rating": 4.7,
        "inventory": 80,
        "image_url": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=900&q=80",
        "description": "Creamy salted butter for breakfast, baking, cooking, and sandwiches.",
    },
    {
        "sku": "GROC-TATA-SALT-1KG",
        "name": "Tata Salt Iodized 1 kg",
        "brand": "Tata",
        "category": "Grocery",
        "subcategory": "Salt and Sugar",
        "size": "1 kg",
        "price": 28,
        "mrp": 32,
        "discount_percent": 13,
        "rating": 4.6,
        "inventory": 220,
        "image_url": "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=900&q=80",
        "description": "Trusted iodized salt for balanced taste and everyday cooking needs.",
    },
    {
        "sku": "SHOE-NIKE-RUN-SWIFT3",
        "name": "Nike Run Swift 3 Running Shoes",
        "brand": "Nike",
        "category": "Shoes",
        "subcategory": "Running Shoes",
        "gender": "Men",
        "color": "Black",
        "size": "UK 9",
        "price": 4295,
        "mrp": 5995,
        "discount_percent": 28,
        "rating": 4.4,
        "inventory": 28,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
        "description": "Comfortable running shoes with cushioned support and grippy everyday traction.",
    },
    {
        "sku": "SHOE-ADIDAS-QUESTAR",
        "name": "Adidas Questar 3 Sneakers",
        "brand": "Adidas",
        "category": "Shoes",
        "subcategory": "Sneakers",
        "gender": "Men",
        "color": "White",
        "size": "UK 8",
        "price": 3799,
        "mrp": 5599,
        "discount_percent": 32,
        "rating": 4.3,
        "inventory": 34,
        "image_url": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80",
        "description": "Sporty lace-up sneakers with breathable upper, soft cushioning, and versatile street style.",
    },
    {
        "sku": "SHOE-PUMA-CARINA",
        "name": "Puma Carina Street Shoes",
        "brand": "Puma",
        "category": "Shoes",
        "subcategory": "Casual Shoes",
        "gender": "Women",
        "color": "Pink",
        "size": "UK 6",
        "price": 2999,
        "mrp": 4499,
        "discount_percent": 33,
        "rating": 4.2,
        "inventory": 25,
        "image_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80",
        "description": "Stylish casual shoes with a platform profile, padded feel, and durable outsole.",
    },
    {
        "sku": "SHOE-BATA-COMFIT",
        "name": "Bata Comfit Formal Shoes",
        "brand": "Bata",
        "category": "Shoes",
        "subcategory": "Formal Shoes",
        "gender": "Men",
        "color": "Brown",
        "size": "UK 10",
        "price": 2199,
        "mrp": 2999,
        "discount_percent": 27,
        "rating": 4.0,
        "inventory": 30,
        "image_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=900&q=80",
        "description": "Classic formal shoes with cushioned insole, polished finish, and office-ready comfort.",
    },
    {
        "sku": "JEAN-LEVIS-511-SLIM",
        "name": "Levi's 511 Slim Fit Jeans",
        "brand": "Levi's",
        "category": "Jeans",
        "subcategory": "Slim Fit",
        "gender": "Men",
        "color": "Dark Blue",
        "size": "32",
        "price": 2499,
        "mrp": 3999,
        "discount_percent": 38,
        "rating": 4.5,
        "inventory": 40,
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
        "description": "Slim fit denim jeans with stretch comfort, clean styling, and everyday durability.",
    },
    {
        "sku": "JEAN-WRANGLER-SKINNY",
        "name": "Wrangler Skinny Fit Jeans",
        "brand": "Wrangler",
        "category": "Jeans",
        "subcategory": "Skinny Fit",
        "gender": "Women",
        "color": "Black",
        "size": "30",
        "price": 1899,
        "mrp": 2999,
        "discount_percent": 37,
        "rating": 4.2,
        "inventory": 38,
        "image_url": "https://images.unsplash.com/photo-1475178626620-a4d074967452?auto=format&fit=crop&w=900&q=80",
        "description": "Black skinny jeans with flattering stretch fabric and a polished casual look.",
    },
    {
        "sku": "JEAN-PEPE-REGULAR",
        "name": "Pepe Jeans Regular Fit Denim",
        "brand": "Pepe Jeans",
        "category": "Jeans",
        "subcategory": "Regular Fit",
        "gender": "Men",
        "color": "Light Blue",
        "size": "34",
        "price": 2099,
        "mrp": 3499,
        "discount_percent": 40,
        "rating": 4.1,
        "inventory": 33,
        "image_url": "https://images.unsplash.com/photo-1511196044526-5cb3bcb7071b?auto=format&fit=crop&w=900&q=80",
        "description": "Classic regular fit jeans with a faded wash, sturdy seams, and relaxed comfort.",
    },
    {
        "sku": "JEAN-FLYING-MACHINE-TAPERED",
        "name": "Flying Machine Tapered Jeans",
        "brand": "Flying Machine",
        "category": "Jeans",
        "subcategory": "Tapered Fit",
        "gender": "Men",
        "color": "Indigo",
        "size": "32",
        "price": 1599,
        "mrp": 2799,
        "discount_percent": 43,
        "rating": 4.0,
        "inventory": 45,
        "image_url": "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?auto=format&fit=crop&w=900&q=80",
        "description": "Modern tapered jeans with clean indigo wash and easy styling for daily wear.",
    },
    {
        "sku": "TSH-UNIQLO-CREW-WHT",
        "name": "Uniqlo Supima Cotton Crew T-shirt",
        "brand": "Uniqlo",
        "category": "T-shirts",
        "subcategory": "Crew Neck",
        "gender": "Men",
        "color": "White",
        "size": "L",
        "price": 799,
        "mrp": 999,
        "discount_percent": 20,
        "rating": 4.4,
        "inventory": 90,
        "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
        "description": "Soft cotton crew neck T-shirt with a clean fit and breathable everyday comfort.",
    },
    {
        "sku": "TSH-HM-PRINT-BLK",
        "name": "H&M Printed Relaxed Fit T-shirt",
        "brand": "H&M",
        "category": "T-shirts",
        "subcategory": "Printed T-shirt",
        "gender": "Women",
        "color": "Black",
        "size": "M",
        "price": 699,
        "mrp": 1299,
        "discount_percent": 46,
        "rating": 4.1,
        "inventory": 75,
        "image_url": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
        "description": "Relaxed printed T-shirt with soft fabric, easy drape, and casual weekend style.",
    },
    {
        "sku": "TSH-ROADSTER-POLO-NVY",
        "name": "Roadster Solid Polo T-shirt",
        "brand": "Roadster",
        "category": "T-shirts",
        "subcategory": "Polo",
        "gender": "Men",
        "color": "Navy",
        "size": "XL",
        "price": 599,
        "mrp": 1099,
        "discount_percent": 45,
        "rating": 4.0,
        "inventory": 84,
        "image_url": "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=900&q=80",
        "description": "Solid polo T-shirt with a neat collar, breathable knit, and smart casual appeal.",
    },
]


def upsert_products() -> tuple[int, int]:
    create_mysql_schema()
    db = SessionLocal()
    try:
        hubs = list(db.scalars(select(DeliveryHub).where(DeliveryHub.is_active.is_(True))).all())
        created = 0
        updated = 0

        for item in PRODUCTS:
            product = db.scalar(select(Product).where(Product.sku == item["sku"]))
            if product is None:
                product = Product(**item, slug=unique_slug(db, item["name"]))
                db.add(product)
                db.flush()
                created += 1
            else:
                for key, value in item.items():
                    setattr(product, key, value)
                product.slug = unique_slug(db, item["name"], product.id)
                product.is_active = True
                updated += 1

            for hub in hubs:
                stock = db.scalar(
                    select(ProductHubStock).where(
                        ProductHubStock.product_id == product.id,
                        ProductHubStock.hub_id == hub.id,
                    )
                )
                if stock is None:
                    db.add(ProductHubStock(product_id=product.id, hub_id=hub.id, quantity=product.inventory))
                else:
                    stock.quantity = product.inventory

        db.commit()
        return created, updated
    finally:
        db.close()


if __name__ == "__main__":
    created_count, updated_count = upsert_products()
    print(f"Seeded products. Created: {created_count}, updated: {updated_count}, total batch: {len(PRODUCTS)}")
